version: '3'

services:
  snippet-operations:
    container_name: "snippet-operations"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_KEY}
