version: '3'

services:
  snippet-operations:
    container_name: "snippet-operations"
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8082:8082"
    env_file:
      - .env
