version: '3'

services:
  snippet-operations:
    container_name: "snippet-operations"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
  redis:
    container_name: "redis"
    image: redis:6-alpine
    ports:
        - "6379:6379"