spring:
  application:
    name: snippet-ops
  datasource:
    url:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    properties:
      hibernate:
        temp: use_jdbc_metadata_defaults=false
    hibernate:
      ddl-auto: none
  services:
    snippet:
      permissions: http://snippet-permissions:8080
      runner: http://snippet-runner:8080
      bucket: http://asset_service:8080/v1/asset

okta:
  oauth2:
    issuer: ${AUTH_SERVER_URI}
    audience: ${AUTH0_AUDIENCE}
    client-id: ${AUTH_CLIENT_ID}
    client-secret: ${AUTH_CLIENT_SECRET}
  machine:
    audience: ${MACHINE_AUDIENCE}
    client-id: ${MACHINE_CLIENT_ID}
    client-secret: ${MACHINE_CLIENT_SECRET}
