server:
  port: 8083

# redis host and port parameters
spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# streamKeys to be used by producers
stream:
  keys:
    linting: "lintingStream"
    formatting: "formattingStream"

# groupIds to be used by consumers
groups:
  groups:
    linting: "lintSnippetsOnRuleChange"
    formatting: "formatSnippetsOnRuleChange"
