name: "Continuous Deployment Dev"

on:
  workflow_run:
    workflows: [ "Java CI with Gradle" ]
    branches:
      - dev
    types:
      - completed
jobs:
  push_snippet_operations:
    name: Push snippet-operations image to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          no-cache: true
          tags: ghcr.io/ingsis-group2/snippet-operations-dev:latest
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP_DEV }}
          username: "azureuser"
          key: ${{ secrets.PRIVATE_KEY_DEV }}
          script: |
            cd snippet-infra
            sudo docker compose -f docker-compose.dev.yml stop snippet-operations
            sudo docker compose -f docker-compose.dev.yml pull snippet-operations
            sudo docker compose -f docker-compose.dev.yml up snippet-operations -d --build 
